title: Site

sections:

  drafts:
    headline: Drafts
    type: pages
    status: draft
    image: icon

  unlisted:
    headline: Unlisted
    type: pages
    status: unlisted
    image: icon

  published:
    headline: Published Pages
    type: pages
    status: listed
    image: icon
